[package]
name = "risk_battle_calculator"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.8.4"
itertools = "0.10.3"
clap = { version = "3.0.4", features = ["derive"] }